// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package aws_test

import (
	"context"
	"github.com/aws/aws-sdk-go-v2/service/sns"
	"github.com/aws/aws-sdk-go-v2/service/sqs"
	"github.com/x4b1/messenger/broker/aws"
	"sync"
)

// Ensure, that SNSClientMock does implement aws.SNSClient.
// If this is not the case, regenerate this file with moq.
var _ aws.SNSClient = &SNSClientMock{}

// SNSClientMock is a mock implementation of aws.SNSClient.
//
//	func TestSomethingThatUsesSNSClient(t *testing.T) {
//
//		// make and configure a mocked aws.SNSClient
//		mockedSNSClient := &SNSClientMock{
//			PublishFunc: func(ctx context.Context, params *sns.PublishInput, optFns ...func(*sns.Options)) (*sns.PublishOutput, error) {
//				panic("mock out the Publish method")
//			},
//		}
//
//		// use mockedSNSClient in code that requires aws.SNSClient
//		// and then make assertions.
//
//	}
type SNSClientMock struct {
	// PublishFunc mocks the Publish method.
	PublishFunc func(ctx context.Context, params *sns.PublishInput, optFns ...func(*sns.Options)) (*sns.PublishOutput, error)

	// calls tracks calls to the methods.
	calls struct {
		// Publish holds details about calls to the Publish method.
		Publish []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Params is the params argument value.
			Params *sns.PublishInput
			// OptFns is the optFns argument value.
			OptFns []func(*sns.Options)
		}
	}
	lockPublish sync.RWMutex
}

// Publish calls PublishFunc.
func (mock *SNSClientMock) Publish(ctx context.Context, params *sns.PublishInput, optFns ...func(*sns.Options)) (*sns.PublishOutput, error) {
	callInfo := struct {
		Ctx    context.Context
		Params *sns.PublishInput
		OptFns []func(*sns.Options)
	}{
		Ctx:    ctx,
		Params: params,
		OptFns: optFns,
	}
	mock.lockPublish.Lock()
	mock.calls.Publish = append(mock.calls.Publish, callInfo)
	mock.lockPublish.Unlock()
	if mock.PublishFunc == nil {
		var (
			publishOutputOut *sns.PublishOutput
			errOut           error
		)
		return publishOutputOut, errOut
	}
	return mock.PublishFunc(ctx, params, optFns...)
}

// PublishCalls gets all the calls that were made to Publish.
// Check the length with:
//
//	len(mockedSNSClient.PublishCalls())
func (mock *SNSClientMock) PublishCalls() []struct {
	Ctx    context.Context
	Params *sns.PublishInput
	OptFns []func(*sns.Options)
} {
	var calls []struct {
		Ctx    context.Context
		Params *sns.PublishInput
		OptFns []func(*sns.Options)
	}
	mock.lockPublish.RLock()
	calls = mock.calls.Publish
	mock.lockPublish.RUnlock()
	return calls
}

// Ensure, that SQSClientMock does implement aws.SQSClient.
// If this is not the case, regenerate this file with moq.
var _ aws.SQSClient = &SQSClientMock{}

// SQSClientMock is a mock implementation of aws.SQSClient.
//
//	func TestSomethingThatUsesSQSClient(t *testing.T) {
//
//		// make and configure a mocked aws.SQSClient
//		mockedSQSClient := &SQSClientMock{
//			DeleteMessageFunc: func(contextMoqParam context.Context, deleteMessageInput *sqs.DeleteMessageInput, fns ...func(*sqs.Options)) (*sqs.DeleteMessageOutput, error) {
//				panic("mock out the DeleteMessage method")
//			},
//			GetQueueUrlFunc: func(contextMoqParam context.Context, getQueueUrlInput *sqs.GetQueueUrlInput, fns ...func(*sqs.Options)) (*sqs.GetQueueUrlOutput, error) {
//				panic("mock out the GetQueueUrl method")
//			},
//			ReceiveMessageFunc: func(contextMoqParam context.Context, receiveMessageInput *sqs.ReceiveMessageInput, fns ...func(*sqs.Options)) (*sqs.ReceiveMessageOutput, error) {
//				panic("mock out the ReceiveMessage method")
//			},
//			SendMessageFunc: func(contextMoqParam context.Context, sendMessageInput *sqs.SendMessageInput, fns ...func(*sqs.Options)) (*sqs.SendMessageOutput, error) {
//				panic("mock out the SendMessage method")
//			},
//		}
//
//		// use mockedSQSClient in code that requires aws.SQSClient
//		// and then make assertions.
//
//	}
type SQSClientMock struct {
	// DeleteMessageFunc mocks the DeleteMessage method.
	DeleteMessageFunc func(contextMoqParam context.Context, deleteMessageInput *sqs.DeleteMessageInput, fns ...func(*sqs.Options)) (*sqs.DeleteMessageOutput, error)

	// GetQueueUrlFunc mocks the GetQueueUrl method.
	GetQueueUrlFunc func(contextMoqParam context.Context, getQueueUrlInput *sqs.GetQueueUrlInput, fns ...func(*sqs.Options)) (*sqs.GetQueueUrlOutput, error)

	// ReceiveMessageFunc mocks the ReceiveMessage method.
	ReceiveMessageFunc func(contextMoqParam context.Context, receiveMessageInput *sqs.ReceiveMessageInput, fns ...func(*sqs.Options)) (*sqs.ReceiveMessageOutput, error)

	// SendMessageFunc mocks the SendMessage method.
	SendMessageFunc func(contextMoqParam context.Context, sendMessageInput *sqs.SendMessageInput, fns ...func(*sqs.Options)) (*sqs.SendMessageOutput, error)

	// calls tracks calls to the methods.
	calls struct {
		// DeleteMessage holds details about calls to the DeleteMessage method.
		DeleteMessage []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// DeleteMessageInput is the deleteMessageInput argument value.
			DeleteMessageInput *sqs.DeleteMessageInput
			// Fns is the fns argument value.
			Fns []func(*sqs.Options)
		}
		// GetQueueUrl holds details about calls to the GetQueueUrl method.
		GetQueueUrl []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// GetQueueUrlInput is the getQueueUrlInput argument value.
			GetQueueUrlInput *sqs.GetQueueUrlInput
			// Fns is the fns argument value.
			Fns []func(*sqs.Options)
		}
		// ReceiveMessage holds details about calls to the ReceiveMessage method.
		ReceiveMessage []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// ReceiveMessageInput is the receiveMessageInput argument value.
			ReceiveMessageInput *sqs.ReceiveMessageInput
			// Fns is the fns argument value.
			Fns []func(*sqs.Options)
		}
		// SendMessage holds details about calls to the SendMessage method.
		SendMessage []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// SendMessageInput is the sendMessageInput argument value.
			SendMessageInput *sqs.SendMessageInput
			// Fns is the fns argument value.
			Fns []func(*sqs.Options)
		}
	}
	lockDeleteMessage  sync.RWMutex
	lockGetQueueUrl    sync.RWMutex
	lockReceiveMessage sync.RWMutex
	lockSendMessage    sync.RWMutex
}

// DeleteMessage calls DeleteMessageFunc.
func (mock *SQSClientMock) DeleteMessage(contextMoqParam context.Context, deleteMessageInput *sqs.DeleteMessageInput, fns ...func(*sqs.Options)) (*sqs.DeleteMessageOutput, error) {
	callInfo := struct {
		ContextMoqParam    context.Context
		DeleteMessageInput *sqs.DeleteMessageInput
		Fns                []func(*sqs.Options)
	}{
		ContextMoqParam:    contextMoqParam,
		DeleteMessageInput: deleteMessageInput,
		Fns:                fns,
	}
	mock.lockDeleteMessage.Lock()
	mock.calls.DeleteMessage = append(mock.calls.DeleteMessage, callInfo)
	mock.lockDeleteMessage.Unlock()
	if mock.DeleteMessageFunc == nil {
		var (
			deleteMessageOutputOut *sqs.DeleteMessageOutput
			errOut                 error
		)
		return deleteMessageOutputOut, errOut
	}
	return mock.DeleteMessageFunc(contextMoqParam, deleteMessageInput, fns...)
}

// DeleteMessageCalls gets all the calls that were made to DeleteMessage.
// Check the length with:
//
//	len(mockedSQSClient.DeleteMessageCalls())
func (mock *SQSClientMock) DeleteMessageCalls() []struct {
	ContextMoqParam    context.Context
	DeleteMessageInput *sqs.DeleteMessageInput
	Fns                []func(*sqs.Options)
} {
	var calls []struct {
		ContextMoqParam    context.Context
		DeleteMessageInput *sqs.DeleteMessageInput
		Fns                []func(*sqs.Options)
	}
	mock.lockDeleteMessage.RLock()
	calls = mock.calls.DeleteMessage
	mock.lockDeleteMessage.RUnlock()
	return calls
}

// GetQueueUrl calls GetQueueUrlFunc.
func (mock *SQSClientMock) GetQueueUrl(contextMoqParam context.Context, getQueueUrlInput *sqs.GetQueueUrlInput, fns ...func(*sqs.Options)) (*sqs.GetQueueUrlOutput, error) {
	callInfo := struct {
		ContextMoqParam  context.Context
		GetQueueUrlInput *sqs.GetQueueUrlInput
		Fns              []func(*sqs.Options)
	}{
		ContextMoqParam:  contextMoqParam,
		GetQueueUrlInput: getQueueUrlInput,
		Fns:              fns,
	}
	mock.lockGetQueueUrl.Lock()
	mock.calls.GetQueueUrl = append(mock.calls.GetQueueUrl, callInfo)
	mock.lockGetQueueUrl.Unlock()
	if mock.GetQueueUrlFunc == nil {
		var (
			getQueueUrlOutputOut *sqs.GetQueueUrlOutput
			errOut               error
		)
		return getQueueUrlOutputOut, errOut
	}
	return mock.GetQueueUrlFunc(contextMoqParam, getQueueUrlInput, fns...)
}

// GetQueueUrlCalls gets all the calls that were made to GetQueueUrl.
// Check the length with:
//
//	len(mockedSQSClient.GetQueueUrlCalls())
func (mock *SQSClientMock) GetQueueUrlCalls() []struct {
	ContextMoqParam  context.Context
	GetQueueUrlInput *sqs.GetQueueUrlInput
	Fns              []func(*sqs.Options)
} {
	var calls []struct {
		ContextMoqParam  context.Context
		GetQueueUrlInput *sqs.GetQueueUrlInput
		Fns              []func(*sqs.Options)
	}
	mock.lockGetQueueUrl.RLock()
	calls = mock.calls.GetQueueUrl
	mock.lockGetQueueUrl.RUnlock()
	return calls
}

// ReceiveMessage calls ReceiveMessageFunc.
func (mock *SQSClientMock) ReceiveMessage(contextMoqParam context.Context, receiveMessageInput *sqs.ReceiveMessageInput, fns ...func(*sqs.Options)) (*sqs.ReceiveMessageOutput, error) {
	callInfo := struct {
		ContextMoqParam     context.Context
		ReceiveMessageInput *sqs.ReceiveMessageInput
		Fns                 []func(*sqs.Options)
	}{
		ContextMoqParam:     contextMoqParam,
		ReceiveMessageInput: receiveMessageInput,
		Fns:                 fns,
	}
	mock.lockReceiveMessage.Lock()
	mock.calls.ReceiveMessage = append(mock.calls.ReceiveMessage, callInfo)
	mock.lockReceiveMessage.Unlock()
	if mock.ReceiveMessageFunc == nil {
		var (
			receiveMessageOutputOut *sqs.ReceiveMessageOutput
			errOut                  error
		)
		return receiveMessageOutputOut, errOut
	}
	return mock.ReceiveMessageFunc(contextMoqParam, receiveMessageInput, fns...)
}

// ReceiveMessageCalls gets all the calls that were made to ReceiveMessage.
// Check the length with:
//
//	len(mockedSQSClient.ReceiveMessageCalls())
func (mock *SQSClientMock) ReceiveMessageCalls() []struct {
	ContextMoqParam     context.Context
	ReceiveMessageInput *sqs.ReceiveMessageInput
	Fns                 []func(*sqs.Options)
} {
	var calls []struct {
		ContextMoqParam     context.Context
		ReceiveMessageInput *sqs.ReceiveMessageInput
		Fns                 []func(*sqs.Options)
	}
	mock.lockReceiveMessage.RLock()
	calls = mock.calls.ReceiveMessage
	mock.lockReceiveMessage.RUnlock()
	return calls
}

// SendMessage calls SendMessageFunc.
func (mock *SQSClientMock) SendMessage(contextMoqParam context.Context, sendMessageInput *sqs.SendMessageInput, fns ...func(*sqs.Options)) (*sqs.SendMessageOutput, error) {
	callInfo := struct {
		ContextMoqParam  context.Context
		SendMessageInput *sqs.SendMessageInput
		Fns              []func(*sqs.Options)
	}{
		ContextMoqParam:  contextMoqParam,
		SendMessageInput: sendMessageInput,
		Fns:              fns,
	}
	mock.lockSendMessage.Lock()
	mock.calls.SendMessage = append(mock.calls.SendMessage, callInfo)
	mock.lockSendMessage.Unlock()
	if mock.SendMessageFunc == nil {
		var (
			sendMessageOutputOut *sqs.SendMessageOutput
			errOut               error
		)
		return sendMessageOutputOut, errOut
	}
	return mock.SendMessageFunc(contextMoqParam, sendMessageInput, fns...)
}

// SendMessageCalls gets all the calls that were made to SendMessage.
// Check the length with:
//
//	len(mockedSQSClient.SendMessageCalls())
func (mock *SQSClientMock) SendMessageCalls() []struct {
	ContextMoqParam  context.Context
	SendMessageInput *sqs.SendMessageInput
	Fns              []func(*sqs.Options)
} {
	var calls []struct {
		ContextMoqParam  context.Context
		SendMessageInput *sqs.SendMessageInput
		Fns              []func(*sqs.Options)
	}
	mock.lockSendMessage.RLock()
	calls = mock.calls.SendMessage
	mock.lockSendMessage.RUnlock()
	return calls
}
